apiVersion: v1
kind: Service
metadata:
  name: ranking
  namespace: kube-ai
  labels:
    app: ranking
spec:
  type: LoadBalancer
  selector:
    app: ranking
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000