apiVersion:  extensions/v1beta1
kind: Deployment
metadata:
  name: ranking
  namespace: kube-ai
  labels:
    app: ranking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ranking
  template:
    metadata:
      labels:
        app: ranking
    spec:
      containers:
      - name: ranking
        image: databricksprod.azurecr.io/ranking:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000