apiVersion: v1
kind: Service
metadata:
  name: gpa-matching
  namespace: kube-ai
  labels:
    app: gpa-matching
spec:
  type: LoadBalancer
  selector:
    app: gpa-matching
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000