apiVersion: v1
kind: Service
metadata:
  name: hardskill-matching
  namespace: kube-ai
  labels:
    app: hardskill-matching
spec:
  type: LoadBalancer
  selector:
    app: hardskill-matching
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000